# cannot find fixdep (/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs//fixdep)
# using basic dep data

/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs/libbpf.o: \
 libbpf.c \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdc-predef.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/stdlib.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdlib.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/features.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/glibc-types.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/cdefs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/alltypes.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/alloca.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/limits.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/limits.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/fortify-headers.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/stdio.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdio.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdarg.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/libgen.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/inttypes.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdint.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/stdint.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/limits.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/string.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/string.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/strings.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/strings.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/unistd.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/unistd.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/posix.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/endian.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fcntl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/fcntl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/errno.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/errno.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/ctype.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/unistd.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/unistd-eabi.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/unistd-common.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/err.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/compiler.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/compiler_types.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/compiler-gcc.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/types.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdbool.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stddef.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/types.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm-generic/int-ll64.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/asm/bitsperlong.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/asm-generic/bitsperlong.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/asm-generic/bitsperlong.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/posix_types.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm-generic/posix_types.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/asm/errno.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/asm-generic/errno.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/asm-generic/errno-base.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/kernel.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/assert.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/build_bug.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/byteswap.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/linux/bpf.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/linux/bpf_common.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/linux/btf.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/filter.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/list.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/poison.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/linux/limits.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi/linux/perf_event.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/linux/ioctl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/ioctl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm-generic/ioctl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/byteorder.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/linux/byteorder/little_endian.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/linux/swab.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/asm/swab.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/linux/ring_buffer.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/asm/barrier.h \
 /workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/asm/../../arch/arm/include/asm/barrier.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/linux/version.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/epoll.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/types.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/sys/select.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/select.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/ioctl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/ioctl.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/ioctl_fix.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/mman.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/mman.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/stat.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/stat.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/vfs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/statfs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/statvfs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/statfs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/utsname.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/resource.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/time.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/resource.h \
 /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/libelf.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/elf.h \
 /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/gelf.h \
 /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/zlib.h \
 /workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/include/zconf.h \
 libbpf.h libbpf_common.h bpf.h btf.h str_error.h libbpf_internal.h \
 hashmap.h

cmd_/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs/libbpf.o := arm-openwrt-linux-muslgnueabi-gcc -Wp,-MD,/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs/.libbpf.o.d -Wp,-MT,/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs/libbpf.o -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16=bpftools-5.11.16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/include -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-enum -Werror -Wall -I. -I/workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include -I/workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi -fvisibility=hidden -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D"BUILD_STR(s)=$(pound)s" -c -o /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/staticobjs/libbpf.o libbpf.c
