# Do not edit. Generated by the configure script.
export PATH:=/workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/node-v14.18.1/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/workdir/openwrt/staging_dir/hostpkg/bin/python3.9
PREFIX=/usr
