# cannot find fixdep (/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs//fixdep)
# using basic dep data

/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs/str_error.o: \
 str_error.c \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdc-predef.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/string.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/string.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/features.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/glibc-types.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/sys/cdefs.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/bits/alltypes.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/strings.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/strings.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/fortify-headers.h \
 /workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify/stdio.h \
 /workdir/staging_dir/_p2w_r619ac-128m/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/stdio.h \
 str_error.h

cmd_/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs/str_error.o := arm-openwrt-linux-muslgnueabi-gcc -Wp,-MD,/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs/.str_error.o.d -Wp,-MT,/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs/str_error.o -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -mfloat-abi=hard -fmacro-prefix-map=/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16=bpftools-5.11.16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/usr/include -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include/fortify -I/workdir/openwrt/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-8.4.0_musl_eabi/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libiconv-stub/include -I/workdir/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/usr/lib/libintl-stub/include -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-enum -Werror -Wall -I. -I/workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include -I/workdir/build_dir/_p2w_r619ac-128m/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16/tools/include/uapi -fvisibility=hidden -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D"BUILD_STR(s)=$(pound)s" -c -o /workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/bpftools-lib/bpftools-5.11.16//libbpf/staticobjs/str_error.o str_error.c
