#!/bin/sh -e

libdir="/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/nghttp2-1.43.0/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/nghttp2-1.43.0/lib/includes -I/workdir/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/nghttp2-1.43.0/lib/includes "
export CGO_CPPFLAGS=""
export CGO_LDFLAGS="-L$libdir "
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
