#!/bin/sh
[ -n "${IPKG_INSTROOT}" ] || sed -i '/coremark/d' /etc/crontabs/root
[ -n "${IPKG_INSTROOT}" ] || echo "0 4 * * * /etc/coremark.sh" >> /etc/crontabs/root
[ -n "${IPKG_INSTROOT}" ] || crontab /etc/crontabs/root
